language: node_js
node_js:
- '8'
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - $HOME/miniconda
    - $HOME/.cache/pip
env:
  matrix:
    - GROUP=e2e
  global:
  - MINICONDA_DIR="$HOME/miniconda"
  - GH_REF: github.com/SimonBiggs/scriptedforms.git
install:
- bash ./scripts/travis_install.sh
script:
- bash ./scripts/travis_script.sh