language: node_js
node_js:
- '8'
dist: trusty
sudo: required
services:
  - docker
addons:
  chrome: stable
  sauce_connect:
    no_ssl_bump_domains: "127.0.0.1,localhost"
cache:
  yarn: true
  directories:
    - $HOME/miniconda
    - $HOME/.cache/pip
env:
  matrix:
    - BROWSER="chrome"
      PLATFORM="Windows 7"
    - BROWSER="firefox"
      PLATFORM="Windows 7"
    - BROWSER="edge"
      PLATFORM="Windows 7"
    - BROWSER="safari"
      PLATFORM="OS X 10.9"
    - BROWSER="firefox"
      PLATFORM="Linux"
  global:
  - MINICONDA_DIR="$HOME/miniconda"
  - GH_REF: github.com/SimonBiggs/scriptedforms.git
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
- bash ./scriptedforms/scripts/travis_install.sh
script:
- bash ./scriptedforms/scripts/travis_script.sh