version: "3.6"

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - jupyterhub:jupyterhub
    command: [nginx-debug, '-g', 'daemon off;']

  jupyterhub:
    restart: always
    build: ./jupyterhub
    links:
      - postgres:postgres

  postgres:
    restart: always
    build: ./postgres